### ISSUE TITLE
feat: add style support for "deprecated"

### ISSUE THREAD

**Issue by bshaffer** [googleapis/doc-pipeline#557]
The property and value `status: deprecated` works in the TOC to mark certain classes/pages as deprecated. When a class, method, or parameter have `status: deprecated` we should have a similar way to mark stylistically that it's deprecated.

```yaml
syntax:
      parameters:
        -
          id: data
          var_type: array
          description: 'Optional. Data for populating the Message object.'
          status: deprecated
```

This would render html like the following:

```html
<tr>
      <td><code>{{{id}}}</code></td>
      <td>
        <code>{{#var_type}}{{{var_type}}}{{/var_type}}{{^var_type}}{{{type.specName.0.value}}}{{/var_type}}</code>
        <br>
        {{{description}}}
        {{>partials/uref/parameters}}
 {{if status == deprecated}}
 <aside class="deprecated">
  <b>Deprecated:</b> A note or tip for a deprecated feature, product, or service.
 </aside>
 {{/if status == deprecated}} 
      </td>
    </tr>
```

A feature like this would be useful for all languages!
